// AUTO-GENERATED FILE — DO NOT EDIT
// Generated by scripts/calibration-fit-btts.ts at 2026-01-23T12:52:51.371Z
// Source eval file: scripts/calibration-eval-btts-2024-2025-new-new.json

export type BttsCalibrationConfig = {
	temperature: number;
	updatedAt: string;
	source: string;
};

export const BTTS_CALIBRATION: BttsCalibrationConfig = {
	temperature: 3.0500,
	updatedAt: "2026-01-23T12:52:51.371Z",
	source: "scripts/calibration-eval-btts-2024-2025-new-new.json",
};
