// AUTO-GENERATED FILE — DO NOT EDIT
// Generated by scripts/calibration-fit-btts.ts at 2026-01-21T14:58:25.467Z
// Source eval file: scripts/calibration-eval-btts-2024.json

export type BttsCalibrationConfig = {
	temperature: number;
	updatedAt: string;
	source: string;
};

export const BTTS_CALIBRATION: BttsCalibrationConfig = {
	temperature: 2.5000,
	updatedAt: "2026-01-21T14:58:25.467Z",
	source: "scripts/calibration-eval-btts-2024.json",
};
