// AUTO-GENERATED FILE — DO NOT EDIT
// Generated by scripts/calibration-fit-btts.ts at 2026-01-21T16:42:59.852Z
// Source eval file: scripts/calibration-eval-btts.json

export type BttsCalibrationConfig = {
	temperature: number;
	updatedAt: string;
	source: string;
};

export const BTTS_CALIBRATION: BttsCalibrationConfig = {
	temperature: 3.9500,
	updatedAt: "2026-01-21T16:42:59.852Z",
	source: "scripts/calibration-eval-btts.json",
};
