// AUTO-GENERATED FILE — DO NOT EDIT
// Generated by scripts/calibration-fit.ts at 2026-01-21T13:27:34.019Z
// Source eval file: scripts/calibration-eval-2024.json

export type MatchOutcomeCalibrationConfig = {
	temperature: number;
	updatedAt: string;
	source: string;
};

export const MATCH_OUTCOME_CALIBRATION: MatchOutcomeCalibrationConfig = {
	temperature: 0.7000,
	updatedAt: "2026-01-21T13:27:34.019Z",
	source: "scripts/calibration-eval-2024.json",
};
