// AUTO-GENERATED FILE — DO NOT EDIT
// Generated by scripts/calibration-fit.ts at 2026-01-23T14:50:30.187Z
// Source eval file: scripts/calibration-eval-2024-ml.json

export type MatchOutcomeCalibrationConfig = {
	temperature: number;
	updatedAt: string;
	source: string;
};

export const MATCH_OUTCOME_CALIBRATION: MatchOutcomeCalibrationConfig = {
	temperature: 0.7000,
	updatedAt: "2026-01-23T14:50:30.187Z",
	source: "scripts/calibration-eval-2024-ml.json",
};
