// AUTO-GENERATED FILE — DO NOT EDIT
// Generated by scripts/calibration-fit.ts at 2026-01-22T23:11:46.478Z
// Source eval file: scripts/calibration-eval-2024-2025-new.json

export type MatchOutcomeCalibrationConfig = {
	temperature: number;
	updatedAt: string;
	source: string;
};

export const MATCH_OUTCOME_CALIBRATION: MatchOutcomeCalibrationConfig = {
	temperature: 0.7000,
	updatedAt: "2026-01-22T23:11:46.478Z",
	source: "scripts/calibration-eval-2024-2025-new.json",
};
