// AUTO-GENERATED FILE — DO NOT EDIT
// Generated by scripts/calibration-fit-goals.ts at 2026-01-22T23:11:56.972Z
// Source eval file: scripts/calibration-eval-goals-2024-2025-new.json

export type TotalGoalsCalibrationConfig = {
	temperature: number;
	updatedAt: string;
	source: string;
};

export const TOTAL_GOALS_CALIBRATION: TotalGoalsCalibrationConfig = {
	temperature: 2.5500,
	updatedAt: "2026-01-22T23:11:56.972Z",
	source: "scripts/calibration-eval-goals-2024-2025-new.json",
};
