// AUTO-GENERATED FILE — DO NOT EDIT
// Generated by scripts/calibration-fit-goals.ts at 2026-01-21T16:45:15.553Z
// Source eval file: scripts/calibration-eval-goals.json

export type TotalGoalsCalibrationConfig = {
	temperature: number;
	updatedAt: string;
	source: string;
};

export const TOTAL_GOALS_CALIBRATION: TotalGoalsCalibrationConfig = {
	temperature: 3.6500,
	updatedAt: "2026-01-21T16:45:15.553Z",
	source: "scripts/calibration-eval-goals.json",
};
