// AUTO-GENERATED FILE — DO NOT EDIT
// Generated by scripts/calibration-fit-goals.ts at 2026-01-23T12:52:52.811Z
// Source eval file: scripts/calibration-eval-goals-2024-2025-new-new.json

export type TotalGoalsCalibrationConfig = {
	temperature: number;
	updatedAt: string;
	source: string;
};

export const TOTAL_GOALS_CALIBRATION: TotalGoalsCalibrationConfig = {
	temperature: 2.0000,
	updatedAt: "2026-01-23T12:52:52.811Z",
	source: "scripts/calibration-eval-goals-2024-2025-new-new.json",
};
