import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import {
	applyBinaryTemperatureScaling,
	assertProb,
	clamp,
} from "../src/modules/betting-insights/utils/calibration-utils";

type EvalRow = {
	probOver: number;
	probUnder: number;
	actual: "OVER" | "UNDER";
	line?: number;
};

const logLossBinary = (rows: EvalRow[], temperature = 1) => {
	let sum = 0;
	for (const [index, row] of rows.entries()) {
		if (row.actual !== "OVER" && row.actual !== "UNDER") {
			throw new Error(
				`Invalid actual value at row ${index}: ${JSON.stringify(row.actual)}`,
			);
		}
		assertProb(row.probOver, "probOver", index);
		assertProb(row.probUnder, "probUnder", index);
		const scaledOver = applyBinaryTemperatureScaling(row.probOver, temperature);
		const p = row.actual === "OVER" ? scaledOver : 1 - scaledOver;
		if (!Number.isFinite(p) || p <= 0 || p > 1) {
			throw new Error(
				`Invalid probability for actual=${row.actual} at row ${index}: ${JSON.stringify(
					p,
				)}`,
			);
		}
		sum += -Math.log(clamp(p, 1e-6, 1));
	}
	return sum / rows.length;
};

const main = async () => {
	const file = process.argv[2];
	const outputArg = process.argv.findIndex((arg) => arg === "--output");
	const outputPath =
		outputArg !== -1
			? process.argv[outputArg + 1]
			: resolve(
					__dirname,
					"../src/modules/betting-insights/config/total-goals-calibration.ts",
				);

	if (!file) {
		throw new Error("Usage: bun scripts/calibration-fit-goals.ts <eval.json>");
	}

	const parsed = JSON.parse(readFileSync(file, "utf-8"));
	if (!Array.isArray(parsed)) {
		throw new Error("Expected JSON array for eval rows.");
	}

	const rows = parsed as EvalRow[];
	if (!rows.length) throw new Error("No rows to evaluate.");

	const minT = 0.5;
	const maxT = 4.5;
	const step = 0.05;
	let bestT = 1;
	let bestLoss = Number.POSITIVE_INFINITY;

	for (let t = minT; t <= maxT + 1e-9; t += step) {
		const loss = logLossBinary(rows, t);
		if (loss < bestLoss) {
			bestLoss = loss;
			bestT = t;
		}
	}

	const baseline = logLossBinary(rows, 1);
	const now = new Date().toISOString();
	const source = file.replace(/\\/g, "/");

	const contents = `// AUTO-GENERATED FILE — DO NOT EDIT
// Generated by scripts/calibration-fit-goals.ts at ${now}
// Source eval file: ${source}

export type TotalGoalsCalibrationConfig = {
	temperature: number;
	updatedAt: string;
	source: string;
};

export const TOTAL_GOALS_CALIBRATION: TotalGoalsCalibrationConfig = {
	temperature: ${bestT.toFixed(4)},
	updatedAt: "${now}",
	source: "${source}",
};
`;

	writeFileSync(outputPath, contents);
	console.log(
		`✅ [Calibration] Best temperature=${bestT.toFixed(4)} (logloss ${bestLoss.toFixed(
			6,
		)}; baseline ${baseline.toFixed(6)})`,
	);
	console.log(`✅ [Calibration] Wrote ${outputPath}`);
};

main().catch((err) => {
	console.error("Error in main:", err);
	process.exit(1);
});
